// Browser-only demo workspace (inside the Loom app the native snapshot
// replaces this on first fetch). Content mirrors the owner's real learning
// genre so the manuscript reads true.

import type { NativeReflectionCase } from '../reflection/nativeReflectionSnapshot';

export const DEMO_WORKBENCH_CASES: NativeReflectionCase[] = [
  {
    id: 'demo-market-making',
    title: 'Market Making · FINS3666',
    project: 'Learning pass',
    status: 'Second pass ready',
    updatedAt: '21:40',
    summary: 'Week 1 Notes.pdf stays primary; Loom records anchored learning around it.',
    tags: ['learning', 'sidecar', 'pdf'],
    sources: [
      {
        id: 'src-week1',
        folder: 'Input',
        label: 'Week 1 Notes.pdf',
        kind: 'pdf',
        meta: '20 pages',
        excerpt: 'Introduction to market making and the limit order book.',
      },
    ],
    steps: [{ id: 'input', title: 'Input', subtitle: 'What actually happened', items: [] }],
    messages: [],
    traceRecords: [
      {
        schemaVersion: 1,
        id: 'demo-r1',
        kind: 'captured',
        traceType: 'selected word',
        sourceAnchor: 'Week 1 Notes.pdf, page 2',
        focus: 'vocabulary',
        text: 'trajectories',
        evidence: [{ label: 'anchor precision', value: 'file+page' }],
        createdAt: 804700000,
        legacyItem: 'Captured selected word from Week 1 Notes.pdf, page 2 [vocabulary]: trajectories',
      },
      {
        schemaVersion: 1,
        id: 'demo-r2',
        kind: 'captured',
        traceType: 'user trace',
        sourceAnchor: 'Week 1 Notes.pdf, page 4',
        focus: 'user meaning',
        text: 'The book is the market: every chart and ticker is derived from these two stacks of resting orders.',
        evidence: [{ label: 'anchor precision', value: 'file+page' }],
        createdAt: 804700400,
        legacyItem: 'Captured user trace from Week 1 Notes.pdf, page 4 [user meaning]: The book is the market…',
      },
      {
        schemaVersion: 1,
        id: 'demo-r3',
        kind: 'captured',
        traceType: 'user trace',
        sourceAnchor: 'Week 1 Notes.pdf, page 9',
        focus: 'user meaning',
        text: 'An IOC is just a faster limit order.',
        evidence: [{ label: 'anchor precision', value: 'file+page' }],
        createdAt: 804700800,
        legacyItem: 'Captured user trace from Week 1 Notes.pdf, page 9 [user meaning]: An IOC is just a faster limit order.',
      },
      {
        schemaVersion: 1,
        id: 'demo-r4',
        kind: 'captured',
        traceType: 'user trace',
        sourceAnchor: 'Week 1 Notes.pdf, page 9',
        focus: 'correction',
        text: 'correction: An IOC never rests in the book — it takes liquidity; a limit order provides it. Market makers live on the providing side.',
        evidence: [{ label: 'anchor precision', value: 'file+page' }],
        createdAt: 804701200,
        legacyItem: 'Captured user trace from Week 1 Notes.pdf, page 9 [correction]: …',
      },
      {
        schemaVersion: 1,
        id: 'demo-r5',
        kind: 'captured',
        traceType: 'user trace',
        sourceAnchor: 'Week 1 Notes.pdf, page 14',
        focus: 'question',
        text: 'Why does my PnL move while my own orders never traded? closes when: I reproduce one minute of mark-to-market from tick history',
        evidence: [{ label: 'anchor precision', value: 'file+page' }],
        createdAt: 804701600,
        legacyItem: 'Captured user trace from Week 1 Notes.pdf, page 14 [question]: …',
      },
      {
        schemaVersion: 1,
        id: 'demo-r6',
        kind: 'captured',
        traceType: 'user trace',
        sourceAnchor: 'Week 1 Notes.pdf, page 17',
        focus: 'principle',
        text: 'principle: Quote only when you know your out — decide how the inventory leaves before the bid goes in.',
        evidence: [{ label: 'anchor precision', value: 'file+page' }],
        createdAt: 804702000,
        legacyItem: 'Captured user trace from Week 1 Notes.pdf, page 17 [principle]: …',
      },
    ],
  },
  {
    id: 'demo-excel-pass',
    title: 'AUDUSD Price History',
    project: 'Learning pass',
    status: 'Reading',
    updatedAt: '19:05',
    summary: 'Excel data pass on the price-history worksheet.',
    tags: ['learning', 'sidecar', 'xlsx'],
    sources: [
      {
        id: 'src-audusd',
        folder: 'Input',
        label: 'Loom Excel Learning Table.csv',
        kind: 'csv',
        meta: '1 sheet',
        excerpt: 'Price History: AUDUSD',
      },
    ],
    steps: [{ id: 'input', title: 'Input', subtitle: 'What actually happened', items: [] }],
    messages: [],
    traceRecords: [
      {
        schemaVersion: 1,
        id: 'demo-x1',
        kind: 'captured',
        traceType: 'selected data',
        sourceAnchor: 'Loom Excel Learning Table.csv',
        focus: 'data',
        text: 'Price History: AUDUSD',
        evidence: [{ label: 'anchor precision', value: 'file' }],
        createdAt: 804690000,
        legacyItem: 'Captured selected data from Loom Excel Learning Table.csv [data]: Price History: AUDUSD',
      },
    ],
  },
];
