import Foundation

/// The LLM wiki's curriculum spine, decoded from `wiki-manifest.json`
/// (generated by scripts/build-wiki-manifest.ts from lib/nav.ts — the single
/// source of truth). Native navigation (LIBRARY rail, reader prev/next,
/// folio lines) reads THIS; it never parses wiki HTML.
struct WikiChapter: Codable, Identifiable, Equatable {
    let slug: String
    let title: String
    let section: String
    /// 0-based position within the whole spine (reading order).
    let order: Int
    /// 1-based position within its section — drives "iii of vi" folios.
    let positionInSection: Int
    let sectionSize: Int
    let href: String

    var id: String { slug }
}

struct WikiManifest: Codable, Equatable {
    let generatedFrom: String
    let version: Int
    let sections: [String]
    let chapters: [WikiChapter]
}

/// One LIBRARY-rail group: a wiki section and its chapters in reading order.
struct WikiRailSection: Identifiable, Equatable {
    let section: String
    let chapters: [WikiChapter]
    var id: String { section }
}

enum WikiCurriculum {
    /// Decode a manifest blob. Refuses future major versions rather than
    /// misreading them.
    static func load(from data: Data) throws -> WikiManifest {
        let manifest = try JSONDecoder().decode(WikiManifest.self, from: data)
        guard manifest.version == 1 else {
            throw CocoaError(.coderInvalidValue, userInfo: [
                NSLocalizedDescriptionKey: "wiki-manifest version \(manifest.version) is newer than this build understands",
            ])
        }
        return manifest
    }

    /// Resolution order for the bundled manifest: the staged web bundle
    /// (Resources/web/wiki-manifest.json). Nil when the wiki isn't staged
    /// (Debug builds without an export) — callers degrade to no library.
    static func loadBundled(bundle: Bundle = .main) -> WikiManifest? {
        guard let url = bundle.resourceURL?
            .appendingPathComponent("web", isDirectory: true)
            .appendingPathComponent("wiki-manifest.json"),
            let data = try? Data(contentsOf: url) else { return nil }
        return try? load(from: data)
    }

    /// Lowercase roman numeral for folio lines ("iii of vi"). Sections are
    /// small; supports 1…399 which is far beyond any real section.
    static func romanFolio(_ n: Int) -> String {
        guard n > 0 else { return "\(n)" }
        let table: [(Int, String)] = [
            (100, "c"), (90, "xc"), (50, "l"), (40, "xl"),
            (10, "x"), (9, "ix"), (5, "v"), (4, "iv"), (1, "i"),
        ]
        var value = n
        var out = ""
        for (weight, glyph) in table {
            while value >= weight {
                out += glyph
                value -= weight
            }
        }
        return out
    }

    /// The running-head line the wiki page itself shows ("finetuning ·
    /// iii of vi") — derived natively so rail rows and reader chrome can
    /// echo the book's own vocabulary without scraping HTML.
    static func folioLine(for chapter: WikiChapter) -> String {
        "\(chapter.section.lowercased()) · \(romanFolio(chapter.positionInSection)) of \(romanFolio(chapter.sectionSize))"
    }

    /// The LIBRARY rail's shape: the spine grouped into its sections (in
    /// manifest order), each section's chapters in reading order. Zero
    /// clustering — this is the book's own table of contents, not a re-sort.
    /// The sidebar renders these as section headers + chapter rows; the reader
    /// opens a row via its slug. Sections with no chapters are dropped.
    static func railSections(in manifest: WikiManifest) -> [WikiRailSection] {
        manifest.sections.compactMap { section in
            let chapters = manifest.chapters
                .filter { $0.section == section }
                .sorted { $0.order < $1.order }
            return chapters.isEmpty ? nil : WikiRailSection(section: section, chapters: chapters)
        }
    }

    /// The wiki quote's back-link (the wedge loop, wiki edition): a
    /// `loom://anchor?wiki=<slug>[&frag=…]` the note's locator glyph carries,
    /// so clicking a wiki quote jumps back to its chapter the way a PDF quote
    /// jumps to its page.
    static func wikiAnchorURL(slug: String, fragment: String?) -> String {
        var comps = URLComponents()
        comps.scheme = "loom"
        comps.host = "anchor"
        var items = [URLQueryItem(name: "wiki", value: slug)]
        if let fragment, !fragment.isEmpty {
            items.append(URLQueryItem(name: "frag", value: fragment))
        }
        comps.queryItems = items
        return comps.string ?? "loom://anchor?wiki=\(slug)"
    }

    /// Parse the chapter slug out of a wiki anchor, or nil when the link is a
    /// PDF (`src=`) anchor or not a loom anchor at all — so the two routes
    /// never shadow each other.
    static func wikiSlugFromAnchor(_ raw: String) -> String? {
        guard raw.hasPrefix("loom://anchor"), let comps = URLComponents(string: raw),
              let slug = comps.queryItems?.first(where: { $0.name == "wiki" })?.value,
              !slug.isEmpty else { return nil }
        return slug
    }

    /// Prev/next along the whole spine (reading order), nil at the edges.
    static func neighbors(of slug: String, in manifest: WikiManifest) -> (prev: WikiChapter?, next: WikiChapter?) {
        guard let index = manifest.chapters.firstIndex(where: { $0.slug == slug }) else {
            return (nil, nil)
        }
        let prev = index > 0 ? manifest.chapters[index - 1] : nil
        let next = index + 1 < manifest.chapters.count ? manifest.chapters[index + 1] : nil
        return (prev, next)
    }
}
