import XCTest
@testable import Loom

// MARK: - CleanTextParityTests
//
// Phase 2 of the ingest-extractor-refactor plan
// (`plans/ingest-extractor-refactor.md` §4 Phase 2, deliverable D).
//
// Pins byte-for-byte parity between the Swift `CleanText.apply()` port
// and the canonical Node `cleanText()` reference in
// `scripts/ingest-knowledge.ts` (lines 255–347) / its executable twin
// `scripts/node-cleantext-wrapper.mjs`.
//
// The `parityFixtures` table below was generated by feeding each raw
// input through `node scripts/node-cleantext-wrapper.mjs --file <f>`
// and capturing the stdout byte-for-byte (see `/tmp/generate-goldens.py`
// in the Phase 2 work log). If the Node pipeline ever changes, rerun
// that generator and paste the new tuples here. Any ad-hoc drift in
// Swift-only cleaning MUST first be landed in the Node side.
//
// These tests do NOT shell out to Node at runtime — keeping the
// test-bundle hermetic matters for CI + offline runs. The "Node is
// canonical" claim is protected by the generation step, not the test
// runner. `scripts/node-cleantext-wrapper.mjs` is committed so the
// generator is reproducible.
//
// ### Corpus coverage
//
// • Control transforms: basic reflow, blank-line collapse, CRLF/CR
//   normalization, NBSP + zero-width stripping, stray-dot cleanup.
// • TOC dot-leaders (`.`), middot leaders (`·`), underscore leaders (`_`).
// • Hyphen word-break reflow across lines.
// • Repeated header/footer drop (≥4 occurrences).
// • Standalone page numbers + "Page N of M" markers.
// • High-punctuation noise-line drop.
// • Multi-column layout preservation with sentinel markers.
// • Single-line & paragraph reflow edge cases (critical
//   non-overlapping match-advance behavior from `/([^\n])\n([^\n])/g`).
// • A multi-paragraph syllabus snippet that touches most transforms.

final class CleanTextParityTests: XCTestCase {

    // MARK: Full-fixture parity table

    /// (name, raw input, Node-cleanText output). Every row is asserted
    /// byte-for-byte. Generated from `scripts/node-cleantext-wrapper.mjs`
    /// on 2026-04-24; see file header for regeneration instructions.
    private let parityFixtures: [(name: String, raw: String, expected: String)] = [
        ("basic",
         "Line 1\nLine 2\nLine 3",
         "Line 1 Line 2 Line 3"),
        ("blank-lines",
         "A\n\n\n\nB",
         "A\n\nB"),
        ("columns",
         "Week 1                Week 2                Week 3\nPython                R                     Julia\n\nRegular paragraph one.\nRegular paragraph two.",
         "Week 1 · Week 2 · Week 3\nPython · R · Julia\n\nRegular paragraph one. Regular paragraph two."),
        ("crlf",
         "Line A\r\nLine B\rLine C\n",
         "Line A Line B Line C"),
        ("high-punct",
         "Real content\n.,-.,-.,-.,-.,-.,-.,-.\nMore content",
         "Real content More content"),
        ("hyphen-break",
         "This is a sen-\ntence with a broken word.",
         "This is a sentence with a broken word."),
        ("kitchen-sink",
         "COVER PAGE . . . . . . . . . 1\nIntroduction\nContent line one\nContent line two\n\n42\nPage 2 of 10\nHeader Repeats\nContent X\nHeader Repeats\nContent Y\nHeader Repeats\nContent Z\nHeader Repeats\nFinal section wrapped-\nup words",
         "COVER PAGE 1 Introduction Content line one Content line two\n\nContent X Content Y Content Z Final section wrappedup words"),
        ("mixed-leaders",
         "Alpha ______ 12\nBeta ···· 34",
         "Alpha 12 Beta 34"),
        ("nbsp-zwsp",
         "Hello\u{00A0}world\u{200B}foo\n",
         "Hello worldfoo"),
        ("page-numbers",
         "Intro text\n42\nPage 1 of 10\nMore content",
         "Intro text More content"),
        ("quad-reflow",
         "Line A\nLine B\nLine C\nLine D",
         "Line A Line B Line C Line D"),
        ("repeated-header",
         "Syllabus 2026\nContent A\nSyllabus 2026\nContent B\nSyllabus 2026\nContent C\nSyllabus 2026\nContent D",
         "Content A Content B Content C Content D"),
        ("stray-dots",
         "Foo . . . bar",
         "Foo bar"),
        ("syllabus-snippet",
         "Course Overview\n\nBasic information\nLecturer in Charge\nMathieu Fournier\nm.fournier@unsw.edu.au\n\nTeaching Assistant\nMengshi Jia\nm.jia@student.unsw.edu.au",
         "Course Overview\n\nBasic information Lecturer in Charge Mathieu Fournier m.fournier@unsw.edu.au\n\nTeaching Assistant Mengshi Jia m.jia@student.unsw.edu.au"),
        ("toc-leaders",
         "Section name . . . . . . . 31\nAnother . . . . . 45",
         "Section name 31 Another 45"),
        ("triple-reflow",
         "Line A\nLine B\nLine C",
         "Line A Line B Line C"),
    ]

    func testAllParityFixtures() {
        var mismatches: [(String, String, String)] = []
        for (name, raw, expected) in parityFixtures {
            let got = CleanText.applyFull(raw)
            if got != expected {
                mismatches.append((name, expected, got))
            }
        }
        if !mismatches.isEmpty {
            var msg = "\(mismatches.count) fixture(s) diverged from Node cleanText:\n"
            for (name, expected, got) in mismatches {
                msg += "\n  • \(name)\n    expected: \(expected.debugDescription)\n    got:      \(got.debugDescription)"
            }
            XCTFail(msg)
        }
    }

    // MARK: Focused regression tests (redundant with the table above but
    // surface targeted failures with clearer names when CI reports them).

    func testReflowMatchesNodeNonOverlappingReplace() {
        // Critical behavior: JS / V8 `.replace(/.../g)` and Swift
        // NSRegularExpression both advance the scanner past the full
        // match, which means adjacent non-blank lines do NOT all chain
        // on a single pass. See CleanText.swift header comment for
        // the detailed derivation.
        XCTAssertEqual(CleanText.applyFull("A\nB\nC"), "A B\nC")
        XCTAssertEqual(CleanText.applyFull("A\nB\nC\nD"), "A B\nC D")
        // …but longer tokens chain across the whole run because each
        // match consumes only 3 chars, leaving room for the next
        // match to land on a still-reflowable seam.
        XCTAssertEqual(CleanText.applyFull("Line A\nLine B\nLine C"),
                       "Line A Line B Line C")
    }

    func testRemovesRepeatedHeadersPageNoiseAndHyphenBreaks() {
        let raw = """
        Header
        Header
        Header
        Header
        1
        Page 2 of 10
        inter-
          esting results
        """

        XCTAssertEqual(CleanText.applyFull(raw), "interesting results")
    }

    func testPreservesColumnRows() {
        let raw = """
        Week 1    Week 2    Week 3
        Topic A    Topic B    Topic C
        """

        XCTAssertEqual(
            CleanText.applyFull(raw),
            "Week 1 · Week 2 · Week 3\nTopic A · Topic B · Topic C"
        )
    }

    func testStripsSentinelsFromFinalOutput() {
        // Sentinel scalars (U+0001 / U+0002) are an internal-only
        // marker for columnar-row preservation; they must never leak
        // into the public output.
        let raw = """
        A    B    C
        X    Y    Z
        """
        let cleaned = CleanText.applyFull(raw)
        XCTAssertFalse(cleaned.contains("\u{0001}"))
        XCTAssertFalse(cleaned.contains("\u{0002}"))
    }

    func testMaxCharsAppliesAfterCleaning() {
        XCTAssertEqual(CleanText.apply(" A   B   C ", maxChars: 3), "A B")
    }

    // MARK: - PDF OCR fallback
    //
    // Scanned / image-only PDFs return no PDFKit `.string` text per page.
    // `PDFExtraction.extract(pageTexts:ocrPageTexts:)` re-cleans the Vision
    // OCR lines per page so the deck still produces usable body text. Here
    // the PDFKit pages are empty and the OCR overload supplies the text.

    func testPDFExtractionFallsBackToOCRPageTextWhenPDFKitTextIsEmpty() throws {
        // Two scanned pages: PDFKit returned empty strings, Vision OCR
        // recovered the lines below.
        let pdfKitPages = ["", ""]
        let ocrPageTexts: [[String]] = [
            ["Lecture 4: Demand", "When prices fall the demand curve shifts right"],
            ["Welfare", "consumer surplus rises as quantity expands"],
        ]
        let extracted = try PDFExtraction.extract(
            pageTexts: pdfKitPages,
            ocrPageTexts: ocrPageTexts,
            maxChars: 6000
        )
        XCTAssertTrue(extracted.text.contains("demand curve shifts right"),
                      "OCR page 1 text missing; got: \(extracted.text)")
        XCTAssertTrue(extracted.text.contains("consumer surplus"),
                      "OCR page 2 text missing; got: \(extracted.text)")
        XCTAssertEqual(extracted.pageRanges.count, 2)
    }

    func testEmptyInputIsStable() {
        XCTAssertEqual(CleanText.apply(""), "")
        XCTAssertEqual(CleanText.apply("   \n  \n  "), "")
    }

    // MARK: Syllabus corpus parity vs Node re-clean
    //
    // For every `<slug>.input.txt` under Tests/fixtures/syllabus/
    // (already-cleaned output of the Node pipeline), pipe it through
    // BOTH Swift `CleanText.applyFull()` AND the Node CLI wrapper
    // `scripts/node-cleantext-wrapper.mjs`; assert byte-for-byte
    // equality between Swift and Node on the re-clean pass.
    //
    // Why re-clean instead of clean-from-raw? Committing ~80 KB of
    // binary PDF fixtures into the test bundle is overkill for a unit
    // test. The Node-produced `input.txt` is a realistic workload for
    // the cleaner (4–8 KB, real syllabus prose, TOC leaders, repeated
    // headers, column-like rows) and exercises every transform at
    // scale. The re-clean pass is the strictest possible parity check:
    // any Swift transform that behaves differently from Node on any
    // input — idempotent or not — surfaces as a byte diff here.
    //
    // Guarded by `LOOM_RUN_NODE_PARITY=1` so a workstation without
    // Node installed or without the repo checked out at the expected
    // absolute path still passes the hermetic parity gate above. CI
    // sets the env var.

    func testSyllabusCorpusMatchesNodeOnRecleanPass() throws {
        let env = ProcessInfo.processInfo.environment
        guard env["LOOM_RUN_NODE_PARITY"] == "1" else {
            throw XCTSkip("set LOOM_RUN_NODE_PARITY=1 to run node-subprocess parity")
        }
        guard let fixturesURL = Self.fixturesDir() else {
            throw XCTSkip("syllabus fixtures dir not found")
        }
        let syllabusDir = fixturesURL.appendingPathComponent("syllabus")
        let fm = FileManager.default
        let all = (try? fm.contentsOfDirectory(at: syllabusDir, includingPropertiesForKeys: nil)) ?? []
        let inputs = all.filter { $0.lastPathComponent.hasSuffix(".input.txt") }
        if inputs.isEmpty {
            throw XCTSkip("syllabus fixtures empty")
        }

        let wrapper = URL(fileURLWithPath: "/Users/yinyiping/Desktop/LOOM/scripts/node-cleantext-wrapper.mjs")
        guard fm.fileExists(atPath: wrapper.path) else {
            throw XCTSkip("node-cleantext-wrapper.mjs missing — is the repo checked out?")
        }

        var driftCount = 0
        var firstDiff: (name: String, index: Int, node: String, swift: String)? = nil
        for url in inputs.sorted(by: { $0.lastPathComponent < $1.lastPathComponent }) {
            let raw = try String(contentsOf: url, encoding: .utf8)
            let swiftOut = CleanText.applyFull(raw)

            let process = Process()
            process.executableURL = URL(fileURLWithPath: "/usr/bin/env")
            process.arguments = ["node", wrapper.path, "--file", url.path]
            let pipe = Pipe()
            process.standardOutput = pipe
            process.standardError = Pipe()
            try process.run()
            process.waitUntilExit()
            guard process.terminationStatus == 0 else {
                XCTFail("node wrapper failed on \(url.lastPathComponent)")
                continue
            }
            let nodeData = pipe.fileHandleForReading.readDataToEndOfFile()
            let nodeOut = String(data: nodeData, encoding: .utf8) ?? ""

            if swiftOut != nodeOut {
                driftCount += 1
                if firstDiff == nil {
                    let swiftArr = Array(swiftOut)
                    let nodeArr = Array(nodeOut)
                    let minlen = min(swiftArr.count, nodeArr.count)
                    var idx = 0
                    while idx < minlen && swiftArr[idx] == nodeArr[idx] { idx += 1 }
                    let start = max(0, idx - 40)
                    let end = min(minlen, idx + 40)
                    firstDiff = (
                        url.lastPathComponent,
                        idx,
                        String(nodeArr[start..<end]),
                        String(swiftArr[start..<end])
                    )
                }
            }
        }
        if driftCount > 0, let d = firstDiff {
            XCTFail("""
                Swift CleanText diverged from Node on \(driftCount) fixture(s) — \
                first mismatch in \(d.name) at char \(d.index):
                  node:  \(d.node.debugDescription)
                  swift: \(d.swift.debugDescription)
                """)
        }
    }

    /// Resolve the repo Tests/fixtures dir from the test bundle's
    /// Resources, falling back to a hard-coded absolute path for
    /// local runs where fixtures are not copied into the bundle.
    private static func fixturesDir() -> URL? {
        let absolute = URL(fileURLWithPath: "/Users/yinyiping/Desktop/LOOM/macos-app/Loom/Tests/fixtures")
        if FileManager.default.fileExists(atPath: absolute.path) {
            return absolute
        }
        // Bundle fallback — if a future xcodegen rev copies fixtures
        // into the .xctest bundle, `Bundle(for:)` will find them.
        let bundle = Bundle(for: CleanTextParityTests.self)
        if let resURL = bundle.resourceURL?.appendingPathComponent("fixtures"),
           FileManager.default.fileExists(atPath: resURL.path) {
            return resURL
        }
        return nil
    }
}
