import XCTest
@testable import Loom

/// Phase 3 unit tests for `SlideDeckExtractor`. Match scoring (5+ samples)
/// + schema Codable round-trip + filename-stem hardening. AI-dependent
/// live extract is schema-checked only.
final class SlideDeckExtractorTests: XCTestCase {
    // MARK: - Match scoring (5+ samples)

    func testMatchScoresPPTXAndKeynoteHighest() {
        XCTAssertEqual(
            SlideDeckExtractor.match(filename: "Lecture 1.pptx", parentPath: "Week 1", sample: ""),
            0.9
        )
        XCTAssertEqual(
            SlideDeckExtractor.match(filename: "Presentation.key", parentPath: "Pitch", sample: ""),
            0.9
        )
    }

    func testMatchScoresSlideDensityPDFMidRange() {
        // Lots of short lines → slide-shaped density.
        let slideLike = (0..<20).map { "Point \($0)" }.joined(separator: "\n")
        XCTAssertEqual(
            SlideDeckExtractor.match(filename: "lecture-slides.pdf", parentPath: "Week 1", sample: slideLike + String(repeating: " ", count: 400)),
            0.7
        )
    }

    func testMatchRejectsProseDensityPDF() {
        // One long paragraph → prose-shaped density, not slides.
        let prose = String(repeating: "A long paragraph that runs for many characters without any line breaks at all. ", count: 10)
        XCTAssertEqual(
            SlideDeckExtractor.match(filename: "textbook-chapter.pdf", parentPath: "Reader", sample: prose),
            0.0
        )
    }

    func testMatchRejectsNonSlideExtensions() {
        XCTAssertEqual(
            SlideDeckExtractor.match(filename: "data.csv", parentPath: "Files", sample: ""),
            0.0
        )
        XCTAssertEqual(
            SlideDeckExtractor.match(filename: "notes.md", parentPath: "Desk", sample: "# h"),
            0.0
        )
    }

    // MARK: - Verification hardening

    func testVerifyAndHardenDemotesFilenameStemQuote() {
        let stems = SyllabusPDFExtractor.filenameStems(from: "LectureDeck_FINS3640.pptx")
        let raw = SlideDeckSchema(
            deckTitle: .found(
                value: "LectureDeck_FINS3640",
                confidence: 0.9,
                sourceSpans: [SourceSpan(docId: "doc", charStart: 0, charEnd: 10, quote: "LectureDeck_FINS3640", verified: true)]
            ),
            author: .notFound(tried: ["title slide"]),
            sections: [],
            topics: []
        )
        let hardened = SlideDeckExtractor.verifyAndHarden(
            schema: raw,
            sourceText: "LectureDeck_FINS3640 and more",
            docId: "doc",
            filenameStems: stems
        )
        guard case .found(_, let conf, let spans) = hardened.deckTitle else {
            return XCTFail("expected found deckTitle")
        }
        XCTAssertEqual(conf, 0.4)
        XCTAssertFalse(spans[0].verified)
        XCTAssertEqual(spans[0].verifyReason, "quote_contains_filename_stem")
    }

    // MARK: - PPTX parse (ZIPFoundation)
    //
    // Fixtures live at `Tests/fixtures/slide-deck/*.pptx`, generated by
    // `Tests/fixtures/slide-deck/generate_fixtures.py`. Each .pptx is a
    // minimal OOXML zip — not a fully valid PowerPoint file, but enough
    // for SlideDeckExtractor (which only reads `ppt/slides/slide*.xml`
    // and `ppt/notesSlides/notesSlide*.xml`).

    func testParsePPTXReturnsAllSlideText() throws {
        guard let url = Self.fixtureURL(name: "minimal.pptx") else {
            throw XCTSkip("fixture minimal.pptx missing — run generate_slide_deck_fixtures.py")
        }
        guard let text = SlideDeckExtractor.parsePPTXText(at: url) else {
            return XCTFail("parsePPTXText returned nil for minimal.pptx")
        }
        XCTAssertTrue(text.contains("Slide 1 title"), "slide 1 title missing; got: \(text)")
        XCTAssertTrue(text.contains("Slide 1 body"), "slide 1 body missing; got: \(text)")
        XCTAssertTrue(text.contains("Slide 2 title"), "slide 2 title missing; got: \(text)")
        XCTAssertTrue(text.contains("Slide 2 body"), "slide 2 body missing; got: \(text)")
        // Notes block should appear after the main slides with the
        // documented separator.
        XCTAssertTrue(text.contains("=== NOTES ==="), "notes separator missing; got: \(text)")
        XCTAssertTrue(text.contains("Speaker note for slide 1"), "notes text missing; got: \(text)")
        // Slide separator appears between slides.
        XCTAssertTrue(text.contains("\n\n---\n\n"), "slide separator missing; got: \(text)")
    }

    func testParsePPTXOrdersSlidesNumerically() throws {
        guard let url = Self.fixtureURL(name: "numeric-ordering.pptx") else {
            throw XCTSkip("fixture numeric-ordering.pptx missing — run generate_slide_deck_fixtures.py")
        }
        guard let text = SlideDeckExtractor.parsePPTXText(at: url) else {
            return XCTFail("parsePPTXText returned nil for numeric-ordering.pptx")
        }
        guard let earlyIdx = text.range(of: "Early slide"),
              let lateIdx = text.range(of: "Late slide")
        else {
            return XCTFail("expected both markers in output; got: \(text)")
        }
        XCTAssertLessThan(
            earlyIdx.lowerBound, lateIdx.lowerBound,
            "slide2.xml (Early slide) must precede slide10.xml (Late slide) — found lexical order instead"
        )
    }

    func testParsePPTXHandlesMalformedSlide() throws {
        guard let url = Self.fixtureURL(name: "malformed-slide.pptx") else {
            throw XCTSkip("fixture malformed-slide.pptx missing — run generate_slide_deck_fixtures.py")
        }
        // Must not crash, must return the text from the good slide, must
        // not invent anything for the bad one.
        let text = SlideDeckExtractor.parsePPTXText(at: url)
        XCTAssertNotNil(text, "parser should recover from one bad slide")
        guard let text else { return }
        XCTAssertTrue(text.contains("Good slide title"), "good slide text missing; got: \(text)")
        XCTAssertTrue(text.contains("Good slide body"), "good slide body missing; got: \(text)")
    }

    // MARK: - PPTX shape / image alt text
    //
    // `alt-text.pptx` carries `p:cNvPr` accessibility title/descr on an
    // embedded picture and a callout shape. Those values are the only
    // machine-readable description of the chart/callout, so the parser
    // must fold them into the slide body.

    func testParsePPTXIncludesShapeAndImageAltText() throws {
        guard let url = Self.fixtureURL(name: "alt-text.pptx") else {
            throw XCTSkip("fixture alt-text.pptx missing — run generate_slide_deck_fixtures.py")
        }
        guard let text = SlideDeckExtractor.parsePPTXText(at: url) else {
            return XCTFail("parsePPTXText returned nil for alt-text.pptx")
        }
        XCTAssertTrue(text.contains("Revenue chart"),
                      "image title alt text missing; got: \(text)")
        XCTAssertTrue(text.contains("Line chart showing revenue increasing from Q1 to Q4"),
                      "image descr alt text missing; got: \(text)")
        XCTAssertTrue(text.contains("Warning callout: churn risk remains elevated"),
                      "shape descr alt text missing; got: \(text)")
    }

    // MARK: - iWork packages (Keynote .key / Pages .pages)
    //
    // iWork packages are zips with `Metadata/*.plist` document properties,
    // `Index/*.iwa` inline body text, and an optional nested QuickLook
    // `Preview.pdf`. The body sweep dedupes standalone slide/page markers
    // (e.g. `Slide 1`, `第 2 页`) that re-appear as labeled titles
    // (`Slide 1: …`). Chinese markers like `第 3 页：机制设计例子` and
    // `第 3 页：先理解再自测` use the full-width colon and are kept intact.

    func testParseKeynoteIWorkArchiveIncludesDocumentMetadata() throws {
        guard let url = Self.fixtureURL(name: "metadata.key") else {
            throw XCTSkip("fixture metadata.key missing")
        }
        guard let text = SlideDeckExtractor.parsePPTXText(at: url) else {
            return XCTFail("parsePPTXText returned nil for metadata.key")
        }
        XCTAssertTrue(text.contains("iWork metadata:"), "metadata section missing; got: \(text)")
        XCTAssertTrue(text.contains("Keynote deck about market design"),
                      "metadata title missing; got: \(text)")
        XCTAssertTrue(text.contains("Avery Scholar"), "metadata author missing; got: \(text)")
    }

    func testParsePagesIWorkArchiveIncludesDocumentMetadata() throws {
        guard let url = Self.fixtureURL(name: "metadata.pages") else {
            throw XCTSkip("fixture metadata.pages missing")
        }
        guard let text = SlideDeckExtractor.parsePPTXText(at: url) else {
            return XCTFail("parsePPTXText returned nil for metadata.pages")
        }
        XCTAssertTrue(text.contains("iWork metadata:"), "metadata section missing; got: \(text)")
    }

    func testParseKeynoteIWorkArchiveIncludesIWAStringBodyText() throws {
        guard let url = Self.fixtureURL(name: "body.key") else {
            throw XCTSkip("fixture body.key missing")
        }
        guard let text = SlideDeckExtractor.parsePPTXText(at: url) else {
            return XCTFail("parsePPTXText returned nil for body.key")
        }
        XCTAssertTrue(text.contains("iWork body text:"), "body section missing; got: \(text)")
        XCTAssertTrue(text.contains("Slide 1: Market design overview"),
                      "UTF-8 IWA body run missing; got: \(text)")
        XCTAssertTrue(text.contains("Matching markets allocate scarce seats"),
                      "UTF-16LE IWA body run missing; got: \(text)")
    }

    func testParsePagesIWorkArchiveIncludesIWAStringBodyText() throws {
        guard let url = Self.fixtureURL(name: "body.pages") else {
            throw XCTSkip("fixture body.pages missing")
        }
        guard let text = SlideDeckExtractor.parsePPTXText(at: url) else {
            return XCTFail("parsePPTXText returned nil for body.pages")
        }
        XCTAssertTrue(text.contains("Page 1: Learning loop overview"),
                      "UTF-8 IWA body run missing; got: \(text)")
        XCTAssertTrue(text.contains("Understanding before self-test"),
                      "UTF-16LE IWA body run missing; got: \(text)")
    }

    func testParseKeynoteIWorkArchiveDropsDuplicateStandaloneSlideMarkers() throws {
        guard let url = Self.fixtureURL(name: "body-duplicate-marker.key") else {
            throw XCTSkip("fixture body-duplicate-marker.key missing")
        }
        guard let text = SlideDeckExtractor.parsePPTXText(at: url) else {
            return XCTFail("parsePPTXText returned nil for body-duplicate-marker.key")
        }
        // The labeled title is kept; the bare `Slide 1` marker preceding it
        // is dropped so the body doesn't carry the marker twice.
        XCTAssertTrue(text.contains("Slide 1: Market design overview"),
                      "labeled title missing; got: \(text)")
        XCTAssertFalse(text.contains("\nSlide 1\n"),
                       "standalone Slide 1 marker should be deduped; got: \(text)")
    }

    func testParsePagesIWorkArchiveDropsDuplicateStandalonePageMarkers() throws {
        guard let url = Self.fixtureURL(name: "body-duplicate-marker.pages") else {
            throw XCTSkip("fixture body-duplicate-marker.pages missing")
        }
        guard let text = SlideDeckExtractor.parsePPTXText(at: url) else {
            return XCTFail("parsePPTXText returned nil for body-duplicate-marker.pages")
        }
        XCTAssertTrue(text.contains("Page 1: Learning loop overview"),
                      "labeled page title missing; got: \(text)")
        XCTAssertFalse(text.contains("\nPage 1\n"),
                       "standalone Page 1 marker should be deduped; got: \(text)")
    }

    func testParsePagesIWorkArchiveExtractsNestedQuickLookPreviewPDF() throws {
        guard let url = Self.fixtureURL(name: "preview-nested.pages") else {
            throw XCTSkip("fixture preview-nested.pages missing")
        }
        guard let text = SlideDeckExtractor.parsePPTXText(at: url) else {
            return XCTFail("parsePPTXText returned nil for preview-nested.pages")
        }
        XCTAssertTrue(text.contains("QuickLook preview:"),
                      "QuickLook preview section missing; got: \(text)")
        XCTAssertTrue(text.contains("Nested QuickLook preview evidence"),
                      "nested preview PDF text missing; got: \(text)")
    }

    // MARK: - Codable round-trip

    func testSchemaCodableRoundTrip() throws {
        let schema = SlideDeckSchema(
            deckTitle: .found(value: "Intro Deck", confidence: 0.9, sourceSpans: []),
            author: .notFound(tried: ["title slide"]),
            sections: [
                SlideSectionEntry(
                    title: .found(value: "Setup", confidence: 0.8, sourceSpans: []),
                    slideRange: .found(value: "slides 1-3", confidence: 0.7, sourceSpans: [])
                ),
            ],
            topics: [.found(value: "Portfolio theory", confidence: 0.7, sourceSpans: [])]
        )
        let encoded = try JSONEncoder().encode(schema)
        let decoded = try JSONDecoder().decode(SlideDeckSchema.self, from: encoded)
        XCTAssertEqual(decoded.sections.count, 1)
        XCTAssertEqual(decoded.topics.count, 1)
    }

    // MARK: - Fixture lookup

    /// Mirror of `CleanTextParityTests.fixturesDir()` — prefers repo path,
    /// falls back to bundle Resources if a future xcodegen rev copies
    /// fixtures into the .xctest bundle.
    private static func fixtureURL(name: String) -> URL? {
        let abs = URL(fileURLWithPath:
            "/Users/yinyiping/Desktop/LOOM/macos-app/Loom/Tests/fixtures/slide-deck")
            .appendingPathComponent(name)
        if FileManager.default.fileExists(atPath: abs.path) {
            return abs
        }
        let bundle = Bundle(for: SlideDeckExtractorTests.self)
        if let resURL = bundle.resourceURL?
            .appendingPathComponent("fixtures/slide-deck/\(name)"),
           FileManager.default.fileExists(atPath: resURL.path) {
            return resURL
        }
        return nil
    }
}
